version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "lambda1-dev"
s3_bucket = "cloudfront030702"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides = 'VPCId=vpc-0b9df6d26c6488729 PrivateSubnetIds=subnet-0bf604215c5364d98,subnet-0a3714e17b138a517 LambdaFunctionName=backend_daily_scheduler'
